### ISSUE TITLE
Status code: 403 Exception: Authentication failed 是cookie的问题吗

### ISSUE THREAD

**Issue by Rlezzo** [X-Zero-L/BingAIChat#3]
2024-04-24 14:17:06,463 bingchat] INFO: Message 2652 triggered bingchat.                    
Status code: 403                                                                             
                                                                                             
https://edgeservices.bing.com/edgesvc/turing/conversation/create                             
[2024-04-24 14:17:06,979 bingchat] ERROR: <class 'TypeError'> occured when bingchat handling 
message 2652.                                                                                
[2024-04-24 14:17:06,979 bingchat] ERROR: call_action() takes 2 positional arguments but 4 we
re given                                                                                     
Traceback (most recent call last):                                                           
  File "/home/rezzo/HoshinoBot/hoshino/modules/BingAIChat/bingchat.py", line 196, in send_bin
g_reply                                                                                      
    ret = await get_bing_reply(msg.strip(), uid, img_url) 
File "/home/rezzo/HoshinoBot/hoshino/modules/BingAIChat/bingchat.py", line 119, in get_bing_reply
    bing = await get_bing(uid)
  File "/home/rezzo/HoshinoBot/hoshino/modules/BingAIChat/bingchat.py", line 129, in get_bing
    'bot': Chatbot(cookies=config.cookies, proxy=config.proxy), # type: ignore
  File "/home/rezzo/HoshinoBot/hoshino/modules/BingAIChat/EdgeGPT/EdgeGPT.py", line 29, in __init__
    Conversation(self.proxy, cookies=cookies),
  File "/home/rezzo/HoshinoBot/hoshino/modules/BingAIChat/EdgeGPT/conversation.py", line 55, in __init__
    raise Exception("Authentication failed")
Exception: Authentication failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rezzo/HoshinoBot/hoshino/msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "/home/rezzo/HoshinoBot/hoshino/modules/BingAIChat/bingchat.py", line 248, in bingchat
    await send_bing_reply(bot, ev, msg, img_url) # type: ignore
  File "/home/rezzo/HoshinoBot/hoshino/modules/BingAIChat/bingchat.py", line 212, in send_bing_reply
    await bot.send_txt2img(ev, err_msg, at_sender=True)
TypeError: call_action() takes 2 positional arguments but 4 were given

**Comment by X-Zero-L** [comment]
先自己去bing官网生成一张图片，然后重新获取cookies文件

**Comment by Rlezzo** [comment]
ok了谢谢
